### ISSUE TITLE
Remove union types.

### ISSUE THREAD

**Issue by Andy2003** [neo4j-contrib/cypher-dsl#143]
The following code will throw a NullPointerException:

```java
import org.neo4j.cypherdsl.core.*;
import org.neo4j.cypherdsl.core.renderer.Renderer;

class Scratch {
    public static void main(String[] args) {

        Node person = Cypher.node("Person").named("person");

        ExposesWhere merge = Cypher.merge(person);
        StatementBuilder.OngoingReadingAndReturn cypher = merge
                .where(Conditions.noCondition())
                .returning(person);

        System.out.println(Renderer.getDefaultRenderer().render(cypher.build()));
    }
}
```

```
Exception in thread "main" java.lang.NullPointerException
	at org.neo4j.cypherdsl.core.DefaultStatementBuilder$MatchBuilder.access$200(DefaultStatementBuilder.java:1101)
	at org.neo4j.cypherdsl.core.DefaultStatementBuilder.where(DefaultStatementBuilder.java:273)
	at Scratch.main(scratch_2.java:12)
```

**Comment by michael-simons** [comment]
While I confirm that NPE, it is not supported anyway.

```java
MERGE (f:Movie {title: 'test'})
WHERE false
return f
```

is not valid Cypher.
I try to prevent that cast.

**Comment by michael-simons** [comment]
Btw the mess of generics in Java without reified types: ```String f = Cypher.merge(person);``` compiles just happily.

**Comment by Andy2003** [comment]
> Btw the mess of generics in Java without reified types: `String f = Cypher.merge(person);` compiles just happily.

Yes but not in Kotlin
