### ISSUE TITLE
Name must be a valid identifier. Why ?

### ISSUE THREAD

**Issue by coooodeXjl** [neo4j-contrib/cypher-dsl#170]
I need to make a Cypher String: match (n) return n.pro

my code :

```
Cypher.match(Cypher.anyNode("n")).returning("n.pro").build().getCypher()
```

It threw an exception.
```
Exception in thread "main" java.lang.IllegalArgumentException: Name must be a valid identifier.
	at org.neo4j.cypherdsl.core.utils.Assertions.isTrue(Assertions.java:59)
	at org.neo4j.cypherdsl.core.SymbolicName.of(SymbolicName.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
...
```

How do i write？

please help me

**Comment by coooodeXjl** [comment]
Why do you have to write this: 
```
Cypher.match(Cypher.anyNode("n")).returning(Cypher.anyNode("n").property("pro")).build().getCypher()
```

**Comment by michael-simons** [comment]
Because `returning(String args)` will create symbolic names from the strings passed (See [SymbolicName](https://s3.amazonaws.com/artifacts.opencypher.org/M15/legacy/railroad/SymbolicName.html). 

A dot is not part of a valid symbolic name. 

I would write your statement as this

```java
var n = Cypher.anyNode("n");
Cypher.match(n).returning(n.property("pro")).build().getCypher()
```

I will update the docs.
