### ISSUE TITLE
Setting and removing a property fails CypherParser

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/cypher-dsl#300]
The following cypher query failed to be parsed with exception  : 

```
CREATE (n:Person) SET n.name = 'John' REMOVE n.birthDate
```

```
class org.neo4j.cypherdsl.core.InternalPropertyImpl cannot be cast to class org.neo4j.cypherdsl.core.Operation (org.neo4j.cypherdsl.core.InternalPropertyImpl and org.neo4j.cypherdsl.core.Operation are in unnamed module of loader 'app')
```

```java
public class CypherParserTest {

    @Test
    void testGettingLabelsCreated() {
        var cypher = "CREATE (n:Person) SET n.name = 'John' REMOVE n.birthDate";

        class LabelCollector implements Function<Expression, Operation> {

            final List<String> labelsSeen = new ArrayList<>();

            @Override
            public Operation apply(Expression expression) {
                Operation op = (Operation) expression;
                op.accept(segment -> {
                    if(segment instanceof NodeLabel) {
                        labelsSeen.add(((NodeLabel) segment).getValue());
                    }
                });
                return op;
            }
        }

        class PropertiesCollector implements Function<Expression, Operation> {
            final List<String> propertiesSeen = new ArrayList<>();

            @Override
            public Operation apply(Expression expression) {
                Operation op = (Operation) expression;
                op.accept(segment -> {
                    if (segment instanceof Property) {
                        propertiesSeen.add(((Property) segment).getName());
                    }
                });
                return op;
            }
        }

        var labelsAdded = new LabelCollector();
        var labelsRemoved = new LabelCollector();
        var propertiesAdded = new PropertiesCollector();
        var propertiesRemoved = new PropertiesCollector();

        var options = Options.newOptions()
                .withCallback(ExpressionCreatedEventType.ON_SET_LABELS,  Operation.class, labelsAdded)
                .withCallback(ExpressionCreatedEventType.ON_REMOVE_LABELS, Operation.class, labelsRemoved)
                .withCallback(ExpressionCreatedEventType.ON_SET_PROPERTY, Operation.class, propertiesAdded)
                .withCallback(ExpressionCreatedEventType.ON_REMOVE_PROPERTY, Operation.class, propertiesRemoved)
                .build();

        CypherParser.parse(cypher, options);

        System.out.println(labelsAdded.labelsSeen);
        System.out.println(labelsRemoved.labelsSeen);
        System.out.println(propertiesAdded.propertiesSeen);
        System.out.println(propertiesRemoved.propertiesSeen);
    }
}
```

Stacktrace : 

```
java.lang.RuntimeException: Unexpected exception

	at org.neo4j.cypherdsl.parser.CypherParser.handle(CypherParser.java:194)
	at org.neo4j.cypherdsl.parser.CypherParser.parseStatement(CypherParser.java:156)
	at org.neo4j.cypherdsl.parser.CypherParser.parse(CypherParser.java:181)
	at com.hume.neo4j.dsl.parser.CypherParserTest.testGettingLabelsCreated(CypherParserTest.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.ClassCastException: class org.neo4j.cypherdsl.core.InternalPropertyImpl cannot be cast to class org.neo4j.cypherdsl.core.Operation (org.neo4j.cypherdsl.core.InternalPropertyImpl and org.neo4j.cypherdsl.core.Operation are in unnamed module of loader 'app')
	at com.hume.neo4j.dsl.parser.CypherParserTest$1PropertiesCollector.apply(CypherParserTest.java:44)
	at com.hume.neo4j.dsl.parser.CypherParserTest$1PropertiesCollector.apply(CypherParserTest.java:39)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at org.neo4j.cypherdsl.parser.CypherDslASTFactory.applyCallbackFor(CypherDslASTFactory.java:149)
	at org.neo4j.cypherdsl.parser.CypherDslASTFactory.removeProperty(CypherDslASTFactory.java:315)
	at org.neo4j.cypherdsl.parser.CypherDslASTFactory.removeProperty(CypherDslASTFactory.java:96)
	at org.neo4j.cypherdsl.parser.internal.parser.javacc.Cypher.RemoveItem(Cypher.java:1362)
	at org.neo4j.cypherdsl.parser.internal.parser.javacc.Cypher.RemoveClause(Cypher.java:1336)
	at org.neo4j.cypherdsl.parser.internal.parser.javacc.Cypher.Clause(Cypher.java:612)
	at org.neo4j.cypherdsl.parser.internal.parser.javacc.Cypher.SingleQuery(Cypher.java:522)
	at org.neo4j.cypherdsl.parser.internal.parser.javacc.Cypher.SingleQueryOrCommand(Cypher.java:330)
	at org.neo4j.cypherdsl.parser.internal.parser.javacc.Cypher.Statement(Cypher.java:262)
	at org.neo4j.cypherdsl.parser.CypherParser.lambda$parseStatement$4(CypherParser.java:158)
	at org.neo4j.cypherdsl.parser.CypherParser.handle(CypherParser.java:186)
	... 68 more
```

**Comment by ikwattro** [comment]
Allright, after some more understanding, the removal is not an operation but an expression. I would say API wise it's a bit unintuitive.

this works 

```
class PropertiesRemoved implements Function<Expression, Expression> {

            final Set<String> propertiesSeen = new HashSet<>();

            @Override
            public Expression apply(Expression expression) {
                String s = ((Property) expression).getName();
                propertiesSeen.add(s);

                return expression;
            }
        }
```

together with 

```
.withCallback(ExpressionCreatedEventType.ON_REMOVE_PROPERTY, Expression.class, propertiesRemoved)
```
