### ISSUE TITLE
Allow function call without result or yield

### ISSUE THREAD

**Issue by Andy2003** [neo4j-contrib/cypher-dsl#349]
Given the following code:

```java
Node n = Cypher.anyNode("n");
ResultStatement statement = Cypher.match(n)
	.call(Cypher.call("apoc.util.validate")
		.withArgs(Predicates.exists(n.property("foo")), Cypher.literalOf("Error"), Cypher.listOf())
		.build())
	.returning(n)
	.build();
```

I would expect the following cypher to be created:

```cypher
Match (n) call apoc.util.validate(Exists(n.foo), "Error", []) return n
```

But I get the Error:

```
java.lang.IllegalArgumentException: Only a statement that returns elements, either via RETURN or YIELD, can be used in a subquery.

	at org.neo4j.cypherdsl.core.Subquery.call(Subquery.java:72)
	at org.neo4j.cypherdsl.core.Subquery.call(Subquery.java:56)
	at org.neo4j.cypherdsl.core.DefaultStatementBuilder.call(DefaultStatementBuilder.java:497)
	at org.neo4j.cypherdsl.core.ExposesSubqueryCall.call(ExposesSubqueryCall.java:53)
```

**Comment by Andy2003** [comment]
The issue is still not solved for queries like:

```cypher
CALL {
CREATE (this0:Movie)
SET this0.title = $this0_title
WITH this0
CALL {
	WITH this0
	CALL apoc.util.validate(NOT(ANY(r IN ["admin"] WHERE ANY(rr IN $auth.roles WHERE r = rr))), "@neo4j/graphql/FORBIDDEN", [0])
    MERGE (this0_genres_connectOrCreate0:Genre { name: $this0_genres_connectOrCreate0_node_name })
    ON CREATE
    SET this0_genres_connectOrCreate0.name = $this0_genres_connectOrCreate0_on_create_name
    MERGE (this0)-[this0_relationship_this0_genres_connectOrCreate0:IN_GENRE]->(this0_genres_connectOrCreate0)
	RETURN COUNT(*)
}
RETURN this0
}
RETURN [
this0 { .title }] AS data
```

**Comment by michael-simons** [comment]
I realised it is better to make this explicit. Thank you for your patience, release will go out soon.
