### ISSUE TITLE
Catalog doesn't support null parameters

### ISSUE THREAD

**Issue by zakjan** [neo4j-contrib/cypher-dsl#785]
Hi,

Since 2023.2.0, null parameters are no longer accepted.

From [docs](https://neo4j-contrib.github.io/cypher-dsl/2023.6.0/#retrieving-parameters):
> In addition, an arbitrary value can be bound to the name via `Cypher.parameter("param", "a value")` or `Cypher.parameter("param").withValue("a value")`. **NULL is a valid value.**

```
Node n = Cypher.anyNode("n");
Statement statement = Cypher.match(n)
        .where(n.property("name").eq(Cypher.parameter("name", null)))
        .returning(n)
        .build();
Map<String, Object> parameters = statement.getCatalog().getParameters();
```

This throws the following error due to the usage of `Map.copyOf` which doesn't support null values:

```
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections$Map1.<init>(ImmutableCollections.java:1105)
	at java.base/java.util.Map.ofEntries(Map.java:1659)
	at java.base/java.util.Map.copyOf(Map.java:1734)
	at org.neo4j.cypherdsl.core.StatementCatalog$PropertyFilter.<init>(StatementCatalog.java:376)
	at org.neo4j.cypherdsl.core.StatementCatalogBuildingVisitor.extractPropertyCondition(StatementCatalogBuildingVisitor.java:340)
	at org.neo4j.cypherdsl.core.StatementCatalogBuildingVisitor.enter(StatementCatalogBuildingVisitor.java:290)
	... 41 more
```

This works with 2023.1.0, where parameters are retrieved with the previous implementation of `statement.getParameters()`.

**Comment by michael-simons** [comment]
Hej, thanks for spotting that issue.
Do you need a backport or is fixing in the next release enough?

**Comment by zakjan** [comment]
Next release is enough, I've upgraded from 2022.8 to 2023.1 (finally with Java 17) for now. Thank you!

**Comment by michael-simons** [comment]
Should be on Maven soon: https://github.com/neo4j-contrib/cypher-dsl/releases/tag/2023.6.1
